name: Deploy to DigitalOcean

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install client dependencies
      run: cd client && npm ci

    - name: Install server dependencies
      run: cd server && npm ci

    - name: Build client
      run: cd client && npm run build

    - name: Build server
      run: cd server && npm run build

    - name: Copy application to Droplet
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        source: .
        target: /var/www/notehub.app

    - name: Restart socket server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        script: sudo systemctl restart notehub
        target: /var/www/notehub.app
